package com.wavemaker.repository.impl;

public class Queries {
    protected static final String INSERT_LEAVE = "INSERT INTO LEAVE_REQUEST (EMPLOYEE_ID,LEAVE_TYPE,FROM_DATE,TO_DATE," +
            "REASON,APPLIED_DATE,STATUS) VALUES (?,?,?,?,?,?,?)";

    protected static final String UPDATE_LEAVE = "UPDATE LEAVE_REQUEST SET STATUS=? WHERE LEAVE_ID=?";

    protected static final String MY_LEAVES = "SELECT * FROM LEAVE_REQUEST WHERE EMPLOYEE_ID=?";

    protected static final String PENDING_TEAM_LEAVES = "SELECT L.EMPLOYEE_ID,L.LEAVE_TYPE,L.FROM_DATE,L.TO_DATE,L.REASON," +
            "L.APPLIED_DATE,L.STATUS,L.LEAVE_ID,E.EMPLOYEE_NAME,E.EMAIL,E.DATE_OF_BIRTH,E.PHONE_NUMBER FROM LEAVE_REQUEST" +
            " L INNER JOIN EMPLOYEES E ON L.EMPLOYEE_ID=E.EMPLOYEE_ID WHERE E.MANAGER_ID=? AND L.STATUS=\"PENDING\"";

    protected static final String VALIDATE_USER = "SELECT EMAIL_ID FROM LOGIN_CREDENTIALS WHERE EMAIL_ID=? AND PASSWORD=?";

    protected static final String GET_EMPLOYEE_ID = "SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMAIL = ?";

    protected static final String GET_USER_NAME = "SELECT EMPLOYEE_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID=?";

    protected static final String GET_ANNUAL_LEAVES = "SELECT TOTAL_LEAVES FROM LEAVE_TYPE WHERE LEAVE_TYPE = ?";

    protected static final String GET_APPLIED_LEAVES_COUNT = "SELECT SUM(TO_DATE-FROM_DATE) FROM LEAVE_REQUEST WHERE " +
            "EMPLOYEE_ID = ? AND LEAVE_TYPE = ? AND STATUS=\"APPROVED\"";

    protected static String GET_EMPLOYEE = "SELECT E.EMPLOYEE_ID,E.EMPLOYEE_NAME,E.DATE_OF_BIRTH,E.EMAIL,E.PHONE_NUMBER," +
            "E.MANAGER_ID,E.GENDER,E1.EMPLOYEE_NAME,E1.EMAIL FROM EMPLOYEES E LEFT JOIN EMPLOYEES E1 ON" +
            " E.MANAGER_ID = E1.EMPLOYEE_ID WHERE E.EMPLOYEE_ID = ?";

    protected static String UPDATE_EMPLOYEE = "UPDATE EMPLOYEES SET EMPLOYEE_NAME=?, DATE_OF_BIRTH = ?, " +
            "PHONE_NUMBER = ?, GENDER = ? WHERE EMPLOYEE_ID=?";

    protected static String GET_FILTERED_LEAVES = "SELECT * FROM LEAVE_REQUEST WHERE EMPLOYEE_ID=? AND STATUS=?";

    protected static String GET_TEAM_MEMBERS = "SELECT * FROM EMPLOYEES WHERE MANAGER_ID = ?";

    protected static String TEAM_LEAVES = "SELECT L.EMPLOYEE_ID,L.LEAVE_TYPE,L.FROM_DATE,L.TO_DATE,L.REASON," +
            "L.APPLIED_DATE,L.STATUS,L.LEAVE_ID,E.EMPLOYEE_NAME,E.EMAIL,E.DATE_OF_BIRTH,E.PHONE_NUMBER FROM LEAVE_REQUEST" +
            " L INNER JOIN EMPLOYEES E ON L.EMPLOYEE_ID=E.EMPLOYEE_ID WHERE E.MANAGER_ID=? AND ( L.STATUS=\"APPROVED\" OR " +
            "L.STATUS = \"REJECTED\")";

}
